# Nixpacks Konfiguration f√ºr Margen-Rechner

[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python run.py"
